### ISSUE TITLE
NullPointerException error loading tactical save

### ISSUE THREAD

**Issue by Tedster59** [rcd47/xcom-2-data#2]
![Image](https://github.com/user-attachments/assets/f9f4822b-bef5-4770-b614-ce3c67a0090e)

Two saves that I was trying to open.
[save_AUTOSAVE- Campaign 468, Mission 35, Turn 15.zip](https://github.com/user-attachments/files/18514813/save_AUTOSAVE-.Campaign.468.Mission.35.Turn.15.zip)

Not sure the best way to reach out or provide any other info needed.

**Comment by rcd47** [comment]
I was going to look at this today, but ran out of time. Will try again next weekend.

**Comment by rcd47** [comment]
Out of curiosity, do you know if the game can load either of these save files? I'm not sure which answer would surprise me more.

In any case, I think I've identified the problem. The NPE occurs on frame 206375 because that frame contains a bad state object. This state object has no object ID, and its PreviousHistoryFrameIndex points to the future (frame 206379). The object does not contain any other fields. Fortunately, the object lookup table contains the name of the state object's class: XComGameState_NMD_Unit. After looking at the list of mods used in these save files, I figured out that was coming from the Nice Mission Debriefing mod.

This weird object actually happened 3 times (in the Hitlog_for_ted save, possibly more in the other one). All 3 involve a moving melee attack that got interrupted, but eventually resumed and caused damage to the target. After scrutinizing NMD's code, I think the problem is in XComGameState_NMD_Root at line 211. This line calls ModifyStateObject, but it uses the state that triggered the event listener instead of the new state that's being constructed. Presumably, that confuses the game's history system and leads to the bad object being saved.

I'll go post a comment on NMD's workshop page, and hopefully the mod author will fix it. I'm going to leave this issue open for now, until I decide whether to put in a workaround for this situation.

**Comment by Tedster59** [comment]
Thanks! the game does load both saves, and I guess whatever Nice Mission Debriefing does isn't enough to cause garbage collection errors on mission end. I was able to identify what I wanted without the save, as I had some event listeners listening for AbilityActivated but not hanging interrupt states themselves.

**Comment by Tedster59** [comment]
I'm also curious, were you manually parsing the save file somehow? related to all of this, I wonder if there's a way to compress history frames together mid-tactical, e.g. by combining all of the StandardMove history states for a unit somehow to reduce save bloat, but that's unrelated to this.

**Comment by rcd47** [comment]
I started my investigation by hacking up the X2DE code a bit so I could set a breakpoint where the NPE happened. Then I examined the variables in a debugger. After that, I looked at the decompressed save file in a hex editor to make sure the object really was missing an ID and there wasn't a bug in the parsing code. When that confirmed the ID was missing, I put a quick and dirty hack into the X2DE code to get around the NPE so I could load the file successfully and examine it in more detail.

As for compressing history frames together: I think the game is already doing that as much as possible. During my own exploration of the history system, I left myself these notes in a mod I haven't released yet:

>	// interruptable abilities cause multiple game state submissions with the same context (see X2GameRuleset, especially SubmitGameStateContext_Internal)
	// note that contexts are mutable, so the context's data can change at each point below
	// first, a state is submitted with the context's interruption status set to Interrupt
	// then, if nothing interrupts, that state gets obliterated from the history and the history index gets reused when the next state is submitted.
	// otherwise the state is left in place and the interruption gets handled.
	// those steps can be repeated multiple times (e.g. when moving, an interrupt state is submitted for every tile traversed)
	// finally, if the interrupted context is still valid (might not be e.g. due to unit dying), a new state is submitted with context interruption status Resume
	// the Resume state is usually the state where the ability applies its changes (see X2Ability TypicalAbility_BuildInterruptGameState)
	// but that's not always 100% true (e.g. during movement, Interrupt states change the tile the unit is on)

Something I forgot to mention in those notes is that if the state does not get interrupted, the "next state" is the same state but with interrupt status set to None.

Regarding movement specifically, the game further optimizes the submitted states. As mentioned above, an interrupt state is submitted for each tile traversed, but if nothing interrupts, the game doesn't submit the state with interrupt status None. Instead, it moves the unit to the next tile and submits a new state with interrupt status Interrupt. Eventually, if nothing interrupts, the movement completes and a state is submitted with interrupt status None for the last tile. So from a history standpoint, it's as if the unit jumped straight to the final tile.

You can see all of this in one of the [testing files](https://github.com/rcd47/xcom-2-data/raw/refs/tags/1.0.0/x2-data-lib/src/test/resources/x2hist/CI%20gatecrasher%20end%20tactical.x2hist) in this repo. Set the frame filter expression to `f.context.summary == 'StandardMove'`. You'll notice that sometimes movements are interrupted and sometimes they're not. E.g. frame 1471, where unit 481 traverses 14 tiles (as you can see in the context tree by drilling into InputContext -> MovementPaths -> 0 -> MovementTiles) but ultimately only one state is in the history, which moved the unit directly to the final tile. This is also true for moving melee abilities like Rend. There's an example of that in frame 2282. Unit 468 traverses 12 tiles, but in that frame, the unit's TileLocation goes from MovementTiles[0] straight to MovementTiles[3].

**Comment by Tedster59** [comment]
Thanks, this is insightful. what I meant for compression, was for a case that comes up on LW HQ missions, where you often spend many turns setting up and you have 40+ enemies making patrol movements for said turns, being able to condense all of those into one state per enemy instead of having a state per enemy per turn, this was one example.

**Comment by Tedster59** [comment]
So, while troubleshooting other stuff, I'm seeing more and more of this error.  if w2 could identify the states/mods that are not correct easily, this could be a massive help to finding and fixing mods that are accidentally editing history

**Comment by rcd47** [comment]
I've released version 1.1.0, which adds a new Problems tab that can identify this issue.

**Comment by Tedster59** [comment]
Thanks for the updates. I've got some more example saves that are erroring out. It's been like 15 years since I've touched Java, if there's a better way for me to debug or provide additional info I'm happy to try to figure out.

![Image](https://github.com/user-attachments/assets/7725c4ad-9b9f-4abd-802c-caa4bd13a74b)

It processes mostly and then crashes near the end. My understanding is both of these saves do successfully load into Tactical.

[save_AUTOSAVE- Campaign 53, Mission 64, Turn 14.zip](https://github.com/user-attachments/files/20151471/save_AUTOSAVE-.Campaign.53.Mission.64.Turn.14.zip)

[save_AUTOSAVE- Campaign 191, Mission 9, Turn 10.zip](https://github.com/user-attachments/files/20151482/save_AUTOSAVE-.Campaign.191.Mission.9.Turn.10.zip)

@rcd47 should I make a new issue or should you reopen this one?

**Comment by Tedster59** [comment]
Ok, I just tested with the original save from the original post and am still seeing the error:

![Image](https://github.com/user-attachments/assets/6a56e4b1-77e7-4f58-8dd1-6c039ad72380)

**Comment by rcd47** [comment]
@Tedster59 I've opened #11 for these problems. It's a NPE but not the same one as before. I'll try to look into this more next weekend, but for now, you can work around the error by opening Preferences -> State Object Summary Script, and commenting out the handling for XCGS_Effect. Just don't forget to reset the script to default after the next release, whenever that ends up being.

**Comment by Tedster59** [comment]
Sounds good, thanks!
